# Pipeline resource configuration
pivnet_token:  xi9eYuRyQPsMNBHDqdTu          				# Pivnet token for downloading resources from Pivnet. Find this token at https://network.pivotal.io/users/dashboard/edit-profile
github_token:  bad283affcf70387d2383038686a6c5967a327bc           	# GitHub token for downloading resources from GitHub

opsman_major_minor_version: ^1\.11\..*$ # PCF Ops Manager minor version to track
ert_major_minor_version: ^1\.11\..*$ # PCF Elastic Runtime minor version to track

git_private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAqmbpon8cXaiUWQhRFg6idvzaQz0k4S9dlnMcrdKv9rNZ3qno
  uLQ6avTon8oYHAWTfG69a5uNvlPYTjh6tm7lepAlYXwOH1iA6BjiDXeZWQpONjEp
  aKU+l/49hiUN0rzqfn76e0BU8oGZrq1MB/hHcZeSD/QgHeGW9AcJkGnHLkKrx5nV
  6oOnQXC4uUFSCP2GdJTXH+kOa0zP7Chxfab3ZmflSAZfHyUOtAvU+ss0p6wLrY1J
  ltZvSz/h8pl/+EJjZY5P9o4BnIBM5rYWfHHzVseFgilemiPgOuN3cNCho+/Ubtjl
  08q5/FVaOuTmhKgVX4ZiJT/Yc5x5viDTMwigrwIDAQABAoIBAEufop5gJRmXwEaG
  /113nziJXOAsWZqqZ7FmYtrtvvQQgpjj9QlLywU+raKEkRCWlO7LQrtn7I8ELOIC
  BMvECYnMQRqzcJ0OrR7UNDZf1qmCflVkmgj8FPxlc6598VWOS89Z0RYz5b8+LxMr
  i6uZzzMlXkhAQqSgQlsIaIEzwJbRfDSZ82skF8/QMcaTdi9cwMZmEaQDgmqboE1c
  pvMfB7tc67kZiNM/6f0HBsXFEhODtnAcap8k8mFr3myNJuoJ5+W6HeNKD3OM02c/
  WLTRqCwvPYvH2MXwCKzBXAuRO4pDYiHCieZp0MVjJkHF0bwLcTYsqoZ8agnyIAiq
  QfnkwjECgYEA3SbJq0I1CiiKdKvHidnvXPoQnodMSpyzBWruj9Pb10JLf4sHXJX+
  9fJ+9em/yQHrFKX3AVEpA02aCHlYHt8PIGuQC+Q//424AfupcMSffZeqsxpPuQnu
  jZHiaTNYYVv6+SJk7Zjs7443fc1ex8kdbpdjQ8CaN7R2UpPdXXutP+kCgYEAxUDm
  ELe/7aSr++gKJGbVMhXcUV0X5em1uowYwfPREWvHNENja95eua3+GWyaKRMMJDX0
  xZiM0L3b7dZYybb90VcCqVCc75qUKPpSnPe2Cf8W0kqCp16cpoaEtusQoG+t+y1t
  +ocTIwJx8FjSSUgYhncJ4Ln7GPMUAP5bjbDj1NcCgYEAsuuUsYfpHYTbL7VixHab
  n595Hqjb4mmQtMtkotyGuksahd/XXuLD2fwNF6u7zEZPCO+VPW2KPu/jtQNndeKF
  fHdJnTVXScxAmOoglemeF6BDLJAW+9+7LrJeeTpfQLWIAVQAT/Ivj0iCQLeM/RoL
  Q9QbLU9/9Z19NSYILH/JFTECgYAPxLNfjMDcB3j0J0WASXQrj9HP80gwyfEMG5zz
  DEGfSeVfyS9OdTVPVJhmgecE94/V6TZLAXnoSfUl2ye34FgD/xeoX1hcUxga+n/W
  Knsz619wqiItrQOK0GAVm0719FeNJ8GN8HRYLR7cns0YrJnBTgzNGTD4ep4TwkGh
  Xw2newKBgQCiKZN+2Nss8S7LGQgBcDaDAfJg2dcEZ2UMKQLdalWOLxJ9DE6CeN9m
  rt0oSk0eiT6dA9woEGSOD9eeUfAB8LCq+waW4hBaztgazKNHIdpFWKU0Y+K4v4Ed
  78zRdQpgXJT3KcuUhZLZXswgDCjnrykrcudAPCfCDdqrBLQz0FeZIg==
  -----END RSA PRIVATE KEY-----



# vCenter configuration
vcenter_host:  192.168.0.110             				# vCenter host or IP
vcenter_usr:   Administrator@vsphere.local           			# vCenter username. If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd:   Notorbix2000! # vCenter password
vcenter_data_center:  DC1      					# vCenter datacenter

# Ops Manager VM configuration
om_vm_host:  192.168.0.116               						# Optional - vCenter host to deploy Ops Manager in
om_data_store:  DS1  							# vCenter datastore name to deploy Ops Manager in
opsman_uri:     opsmanager.system.homelab.fynesy.com 			# FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com
opsman_admin_username:  admin    					# Username for Ops Manager admin account
opsman_admin_password:  pivotal1974! 					# Password for Ops Manager admin account
opsman_timeout_seconds: 900  						# Timeout to wait for Ops Manager to become available
om_ssh_pwd:             pivotal1974!  					# SSH password for Ops Manager (ssh user is ubuntu)
om_decryption_pwd:      pivotal1974!  					# Decryption password for Ops Manager exported settings
om_ntp_servers:         0.pool.ntp.org  				# Comma-separated list of NTP Servers
om_dns_servers:         192.168.0.1  					# Comma-separated list of DNS Servers
om_gateway:             10.0.0.1  					# Gateway for Ops Manager network
om_netmask:             255.255.0.0  					# Netmask for Ops Manager network
om_ip:                  10.0.0.3  					# IP to assign to Ops Manager VM
om_vm_network:          LAN	  					# vCenter network name to use to deploy Ops Manager in
om_vm_name:             OpsMan  					# Name to use for Ops Manager VM
om_disk_type: "thin"      						# Disk type for Ops Manager VM (thick|thin)
om_vm_power_state: true   						# Whether to power on Ops Manager VM after creation

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /DC1/192.168.0.116/C1			#/<Data Center Name>/host/<Cluster Name>
#   resource pool: /Datacenter1/192.168.0.116/C1/Resources/RP1		#/<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool:  /DC1/host/C1/Resources/RP1

ephemeral_storage_names: DS2,DS1 	# Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: DS1,DS2	# Persistent Storage names in vCenter for use by PCF

trusted_certificates:         						# Trusted certificates to be deployed along with all VM's provisioned by BOSH
generate_vm_passwords: true   						# Allow BOSH to generate random passwords for each job.
vm_disk_type: "thin"         						# Disk type for BOSH provisioned VM. (thick|thin)

# AZ configuration for Ops Director
az_1_name:  Zone1                    					# Logical name of availability zone. No spaces or special characters.
az_1_cluster_name: C1           					# Name of cluster in vCenter for AZ1
az_1_rp_name: RP1                					# Resource pool name in vCenter for AZ1

ntp_servers: 0.pool.ntp.org                 				# Comma-separated list of NTP servers to use for VMs deployed by BOSH
ops_dir_hostname:             						# Optional DNS name for Ops Director. Should be reachable from all networks.
enable_vm_resurrector: false 						# Whether to enable BOSH VM resurrector
max_threads: 30               						# Max threads count for deploying VMs

# Network configuration for Ops Director
icmp_checks_enabled: false 						# Enable or disable ICMP checks

infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network: "LAN"        					# vCenter Infrastructure network name
infra_nw_cidr: 10.0.0.0/16                				# Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range: 10.0.0.1-10.0.0.9,10.0.1.0-10.0.255.255 		# Infrastructure network exclusion range 
infra_nw_dns: 192.168.0.1                				# Infrastructure network DNS
infra_nw_gateway: 10.0.0.1        	    				# Infrastructure network Gateway
infra_nw_azs: Zone1         						# Comma seperated list of AZ's to be associated with this network

deployment_network_name: "RUNTIME"
deployment_vsphere_network:  LAN   					# vCenter Deployment network name
deployment_nw_cidr: 10.0.0.0/16         				# Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range: 10.0.0.1-10.0.0.255,10.0.2.0-10.0.255.255	# Deployment network exclusion range
deployment_nw_dns: 192.168.0.1           				# Deployment network DNS
deployment_nw_gateway: 10.0.0.1       					# Deployment network Gateway
deployment_nw_azs: Zone1		     				# Comma seperated list of AZ's to be associated with this network

services_network_name: "SERVICES"
is_service_network: false          # Required select service network option in Ops man true or false

services_vsphere_network: LAN   					# vCenter Services network name
services_nw_cidr: 10.0.0.0/16            				# Services network CIDR, ex: 10.0.0.0/22
services_excluded_range: 10.0.0.1-10.0.1.255,10.0.3.0-10.0.255.255	  # Services network exclusion range
services_nw_dns: 192.168.0.1             				# Services network DNS
services_nw_gateway: 10.0.0.1         					# Services network Gateway
services_nw_azs: Zone1			             	 		# Comma seperated list of AZ's to be associated with this network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: LAN    				# vCenter Dynamic Services network name
dynamic_services_nw_cidr: 10.0.0.0/16            			# Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range: 10.0.0.1-10.0.2.255,10.0.4.0-10.0.255.255	# Dynamic Services network exclusion range
dynamic_services_nw_dns:  192.168.0.1            			# Dynamic Services network DNS
dynamic_services_nw_gateway: 10.0.0.1         				# Dynamic Services network Gateway
dynamic_services_nw_azs: Zone1			     			# Comma seperated list of AZ's to be associated with this network

ert_singleton_job_az:  Zone1       					# AZ to use for deployment of ERT Singleton jobs
ert_errands_to_disable:       # Comma-separated list of errand names to disable before deploy


loggregator_endpoint_port: 	    					# Loggegrator Port. Default is 443
company_name:                 						# Company Name for Apps Manager
company_proxy_domain:         						# If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
syslog_host:
syslog_port:
syslog_protocol:
enable_security_event_logging: false
syslog_drain_buffer_size: 10000

## Wildcard domain certs go here
# Optional. Will be generated if blank using ssl_termination_point below.
ssl_cert:
# Optional. Will be generated if blank using ssl_termination_point below.
ssl_private_key:
ssl_termination_point: haproxy # (external_ssl|external_non_ssl|haproxy)

## Get this from the OPS Manager API docs for your release. Possible values are
## - /api/v0/certificates/generate (for 1.10)
## - /api/v0/rsa_certificates (for 1.9)
om_generate_ssl_endpoint: /api/v0/certificates/generate

disable_http_proxy: true
security_acknowledgement: X  						# Must be set to 'X'. See explanation here: https://docs.pivotal.io/pivotalcf/latest/customizing/config-er-vmware.html#app-security

## TCP routing and routing services
tcp_routing: disable                    # Enable/disable TCP routing (enable|disable)
tcp_routing_ports:                   # A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478
route_services: disable                 # Enable/disable route services (enable|disable)
ignore_ssl_cert_verification: true # Whether to disable SSL cert verification for this environment
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454                # Applications Network Maximum Transmission Unit bytes

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd, and
# smtp_auth_mechanism must also be set.
smtp_address:
smtp_from:
smtp_port:
smtp_user:
smtp_pwd:
smtp_auth_mechanism: # (none|plain|cram-md5)

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:

## Deployment domain names
system_domain: system.homelab.fynesy.com
apps_domain: homelab.fynesy.com

skip_cert_verify: true 							# If true, disable SSL certificate verification for this environment.

disable_insecure_cookies: false 					# If true, disable insecure cookies on the router.

default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
allow_app_ssh_access: true 						# Whether to allow SSH access to application instances

router_request_timeout_in_seconds: 900

ha_proxy_ips: 10.0.1.100           # Comma-separated list of static IPs
router_static_ips:      # Comma-separated list of static IPs
tcp_router_static_ips:  # Comma-separated list of static IPs
ssh_static_ips:         # Comma-separated list of static IPs

mysql_monitor_email: tmfynes@yahoo.com   				# Email address to receive MySQL monitor notifications
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)


#SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

bosh_vm_folder: "pcf_vms"                 # vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_template_folder: "pcf_templates"     # vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_disk_path: "pcf_disk"                # vSphere datastore folder (such as pcf_disk) where attached disk images will be created



## Default resource configuration
consul_server_instances: 1
nats_instances: 1
etcd_tls_server_instances: 1
nfs_server_instances: 1
mysql_proxy_instances: 1
mysql_instances: 1
backup_prepare_instances: 0
ccdb_instances: 0
uaadb_instances: 0
uaa_instances: 1
cloud_controller_instances: 1
ha_proxy_instances: 0
router_instances: 1
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 1
diego_database_instances: 1
diego_brain_instances: 1
diego_cell_instances: 3
doppler_instances: 1
loggregator_traffic_controller_instances: 1
tcp_router_instances: 1

